/**
 * @fileoverview Platform-wide default constants for the PRAJNA platform.
 *
 * This file defines immutable values that are universal across all environments
 * and all modules. Unlike the config layer (which varies per stage), these
 * constants represent fixed platform decisions.
 *
 * When a platform-wide default needs to change (e.g., upgrading the Node.js
 * runtime from 22 to 24), this is the single file to update. All 30+ modules
 * inherit the change automatically.
 *
 * @module foundation/constants/defaults
 */

import { Duration, RemovalPolicy } from 'aws-cdk-lib';
import { Runtime, Architecture, Tracing } from 'aws-cdk-lib/aws-lambda';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { APPLICATION_NAME, APPLICATION_TITLE } from './naming';

// ─────────────────────────────────────────────────────────────────────────────
// AWS Region
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The primary AWS region for all PRAJNA deployments.
 *
 * All modules deploy to this region unless explicitly configured otherwise
 * in their environment config.
 */
export const DEFAULT_REGION = 'ap-south-1' as const;

// ─────────────────────────────────────────────────────────────────────────────
// Lambda Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Platform-standard Lambda runtime.
 *
 * All Lambda functions MUST use this runtime unless a specific function
 * requires a different language (e.g., Python for ML inference).
 * To upgrade the platform runtime, change this single constant.
 */
export const DEFAULT_LAMBDA_RUNTIME = Runtime.NODEJS_20_X;

/**
 * Platform-standard Lambda architecture.
 *
 * ARM64 (Graviton2) provides approximately 20% better price-performance
 * compared to x86_64. All Lambda functions use this unless a dependency
 * requires x86_64 native binaries.
 */
export const DEFAULT_LAMBDA_ARCHITECTURE = Architecture.ARM_64;

/**
 * Default Lambda memory allocation in MB.
 *
 * Individual environments may override this via {@link LambdaConfig.memorySize}.
 * This constant serves as the absolute fallback.
 */
export const DEFAULT_LAMBDA_MEMORY = 256;

/**
 * Default Lambda timeout duration.
 *
 * API-facing functions should use shorter timeouts (10-15s).
 * Background processing functions may use longer timeouts (up to 15 min).
 */
export const DEFAULT_LAMBDA_TIMEOUT = Duration.seconds(30);

/**
 * Maximum Lambda timeout allowed by AWS.
 */
export const MAX_LAMBDA_TIMEOUT = Duration.minutes(15);

/**
 * Default Lambda tracing configuration.
 *
 * Active tracing sends trace data to AWS X-Ray for distributed tracing
 * across Lambda, API Gateway, and other instrumented services.
 */
export const DEFAULT_LAMBDA_TRACING = Tracing.ACTIVE;

/**
 * Default Lambda environment variables applied to every function.
 *
 * These are merged with module-specific environment variables by the
 * {@link SharedLambda} construct. Module-specific variables take precedence.
 */
export const DEFAULT_LAMBDA_ENVIRONMENT: Readonly<Record<string, string>> = {
  NODE_OPTIONS: '--enable-source-maps',
  POWERTOOLS_SERVICE_NAME: APPLICATION_NAME,
  POWERTOOLS_METRICS_NAMESPACE: APPLICATION_NAME,
  LOG_LEVEL: 'INFO',
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// CloudWatch & Monitoring Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default CloudWatch Logs retention period.
 *
 * Individual environments override this via {@link MonitoringConfig.logRetention}.
 * This constant is the absolute fallback.
 */
export const DEFAULT_LOG_RETENTION = RetentionDays.ONE_MONTH;

/**
 * Default number of evaluation periods for CloudWatch alarms.
 *
 * A higher number reduces false positives but increases time-to-alert.
 */
export const DEFAULT_ALARM_EVALUATION_PERIODS = 3;

/**
 * Default alarm statistic period.
 */
export const DEFAULT_ALARM_PERIOD = Duration.minutes(5);

/**
 * Default CloudWatch custom metrics namespace prefix.
 */
export const DEFAULT_METRICS_NAMESPACE = 'Prajna' as const;

// ─────────────────────────────────────────────────────────────────────────────
// S3 Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Maximum file upload size in bytes (50 MB).
 *
 * Used by the Storage module (Module 6) to validate pre-signed upload URLs
 * and by API Gateway to set payload limits.
 */
export const MAX_UPLOAD_SIZE_BYTES = 50 * 1024 * 1024;

/**
 * Pre-signed URL expiration duration.
 *
 * Upload and download pre-signed URLs generated by the Storage module
 * expire after this duration.
 */
export const PRESIGNED_URL_EXPIRATION = Duration.minutes(15);

// ─────────────────────────────────────────────────────────────────────────────
// API Gateway Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default API Gateway throttle rate limit (requests per second).
 */
export const DEFAULT_API_THROTTLE_RATE = 1000;

/**
 * Default API Gateway throttle burst limit.
 */
export const DEFAULT_API_THROTTLE_BURST = 500;

// ─────────────────────────────────────────────────────────────────────────────
// Removal Policy Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default removal policy for non-production environments.
 *
 * DESTROY allows clean teardown of development and QA stacks.
 */
export const NON_PRODUCTION_REMOVAL_POLICY = RemovalPolicy.DESTROY;

/**
 * Default removal policy for production environments.
 *
 * RETAIN ensures that stateful resources (S3, DynamoDB, Cognito)
 * survive stack deletion to prevent accidental data loss.
 */
export const PRODUCTION_REMOVAL_POLICY = RemovalPolicy.RETAIN;

// ─────────────────────────────────────────────────────────────────────────────
// Tagging Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default tag values applied to every resource in the platform.
 *
 * These are the baseline tags. The tagging system ({@link @foundation/tags})
 * merges these with environment-specific and module-specific tags.
 * Module-specific tags take precedence over these defaults.
 */
export const DEFAULT_TAGS: Readonly<Record<string, string>> = {
  Application: APPLICATION_TITLE,
  Project: APPLICATION_NAME,
  ManagedBy: 'AWS-CDK',
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// DynamoDB Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default DynamoDB read capacity units for provisioned tables.
 *
 * Most tables should use PAY_PER_REQUEST billing mode. This constant
 * is only used when provisioned capacity is explicitly required.
 */
export const DEFAULT_DYNAMODB_READ_CAPACITY = 5;

/**
 * Default DynamoDB write capacity units for provisioned tables.
 */
export const DEFAULT_DYNAMODB_WRITE_CAPACITY = 5;

// ─────────────────────────────────────────────────────────────────────────────
// Cognito Defaults
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default Cognito token validity durations.
 *
 * These are absolute fallbacks. Each environment config provides its own
 * values via {@link CognitoConfig}.
 */
export const DEFAULT_ACCESS_TOKEN_VALIDITY = Duration.hours(1);
export const DEFAULT_ID_TOKEN_VALIDITY = Duration.hours(1);
export const DEFAULT_REFRESH_TOKEN_VALIDITY = Duration.days(30);

// ─────────────────────────────────────────────────────────────────────────────
// Platform Metadata
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Current platform version.
 *
 * This version string is:
 * - Published to SSM Parameter Store for cross-module visibility.
 * - Included in resource tags for cost tracking.
 * - Logged at Lambda cold-start for debugging.
 */
export const PLATFORM_VERSION = '1.0.0' as const;

/**
 * Platform owner identifier for tagging and cost allocation.
 */
export const PLATFORM_OWNER = 'PRAJNA-Platform-Team' as const;

/**
 * Cost center identifier for financial tracking.
 */
export const COST_CENTER = 'PRAJNA-Engineering' as const;
